version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=stock_cluster
    volumes:
      - ./hdfs/namenode:/hadoop/dfs/name
      - ./data:/data
    ports:
      - "9870:9870"  
      - "9000:9000"  
    networks:
      - hadoop
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    volumes:
      - ./hdfs/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    volumes:
      - ./hdfs/datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    volumes:
      - ./hdfs/datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  datanode4:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode4
    volumes:
      - ./hdfs/datanode4:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864
    ports:
      - "8088:8088"
    networks:
      - hadoop
  
  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    environment:
      - SERVICE_PRECONDITION=resourcemanager:8088
    networks:
      - hadoop
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 resourcemanager:8088
    ports:
      - "8188:8188"
    networks:
      - hadoop

    

  
  spark-master:
    image: bde2020/spark-master:3.2.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"   
      - "7077:7077"  
    networks:
      - hadoop
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_HOST=spark-master

  spark-worker-1:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-1
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8081:8081"
    networks:
      - hadoop

  spark-worker-2:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-2
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - hadoop

  spark-worker-3:
    image: bde2020/spark-worker:3.2.1-hadoop3.2 
    container_name: spark-worker-3
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
     - hadoop
  
  spark-worker-4:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-4
    environment: 
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - hadoop
      

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.2.1
    container_name: jupyter
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: >
      bash -c "pip install pyspark==3.2.1 &&
               start-notebook.sh --NotebookApp.token='toivu'"
    volumes:
      - ./notebook:/home/jovyan/work
      - ./data:/home/jovyan/data
    networks:
      - hadoop
    

networks:
  hadoop:
    driver: bridge